#!/bin/sh

# It's just a reference implementation.
# You need to modify it according to your local environment.

progCAT="/bin/cat"
progCUT="/usr/bin/cut"
progGREP="/bin/grep"
progECHO="/bin/echo"
progNICE="/bin/nice"
progCURL="/opt/bin/curl"

fileURL="/usr/local/etc/dvdplayer/ims_yv_url_data.dat"
dataURL="`${progCAT} ${fileURL}`"

# Handle 302 redirect
headLOC=`${progCURL} -s -k -I "${dataURL}" | ${progGREP} "Location:"`
while [ $? -eq 0 ]
do
	dataURL=`${progECHO} "${headLOC}" | ${progCUT} -d " " -f 2`
	headLOC=`${progCURL} -s -k -I "${dataURL}" | ${progGREP} "Location:"`
done

exec ${progNICE} -n 6 ${progCURL} -s -k -N -D - -o - "${dataURL}"
